### ISSUE TITLE
Feature Request: support SEP-8 in the Demo Wallet

### ISSUE THREAD

**Issue by howardtw** [stellar/stellar-demo-wallet#62]
### What problem does your feature solve?

We plan on using this demo wallet to validate the POC of SEP-8. We can also use the code in the demo wallet as a reference implementation.

### What would you like to see?

After the SEP-8 support is added to the wallet SDK, we can integrate the wallet SDK into the demo wallet.

### What alternatives are there?

N/A.

**Comment by marcelosalloum** [comment]
Hey @shanzzam, is this an epic? I think we can split it in a few parts:

- [ ] develop backend service used to approve regulated asset transactions
- [ ] deploy this backend service
- [ ] develop a script used to configure the issuer account for regulated assets
- [ ] deploy the TOML file
- [ ] integrate the frontend for `Revised` transactions
- [ ] integrate the frontend for `Rejected` transactions
- [ ] integrate the frontend for `Pending` transactions
- [ ] integrate the frontend for `Action Required` transactions

I'm happy to create issues for these parts once we figure out if this should be an Epic.

**Comment by leighmcculloch** [comment]
Does it make sense to build a backend server straight up? I think you could use any publicly available SEP-8 implementation as a basis, and we might be able to reach out to an operator and ask if they have a testnet server. For example, it looks like this home domain's stellar.toml has an approval server: https://dsq.technology/.well-known/stellar.toml. Maybe we could find out if they have a testnet deployment that we could use to get going.

**Comment by marcelosalloum** [comment]
That's a good point but if we're using a third party server I think it'd be difficult to get our transactions approved+sandwiched without depending too much on external teams.

I was planning on having a dummy server that approves transactions based on their value, e.g. payments with less than 50 MYASSET get approved. This way we can simulate multiple scenarios without depending on external teams.

Another benefit is having a reference server for SEP-8 where other frontend teams could test their implementation.

**Comment by shanzzam** [comment]
We can provide UI to override the dummy server when a user selects to start a SEP-08 transaction. Let's use our test server as default but can be over-written in a text field.

**Comment by marcelosalloum** [comment]
Hum, that is hosted by [django-polaris](https://github.com/stellar/django-polaris/blob/ac9275c93e55ffe1c29eadc02528c50c39acdf8d/example/server/static/polaris/local-stellar.toml) so I'm not sure it would be a good practice.

@JakeUrban: do you think it's ok to have a new currency in https://testanchor.stellar.org/.well-known/stellar.toml if the polaris repo doesn't have any logic related to it? It would look something like this:

```toml
[[CURRENCIES]]
code="GOAT"
issuer="GD5T6IPRNCKFOHQWT264YPKOZAWUMMZOLZBJ6BNQMUGPWGRLBK3U7ZNP"
regulated=true
approval_server="https://goat.io/tx_approve"
approval_criteria="The goat approval server will ensure that transactions are compliant with NFO regulation"
```

**Comment by JakeUrban** [comment]
I think thats fine, the `APPROVAL_SERVER` would point to a different domain so it would be clear a different service implements it.

**Comment by leighmcculloch** [comment]
>Question on the task of "deploy the TOML file": Can we just add to the existing TOML file https://testanchor.stellar.org/.well-known/stellar.toml we have for other testing purposes.

If you do this you'll be binding the deployment of this service with the deployment, which might slow you down. Serving a TOML file is the smallest piece of functionality compared to the rest of the things that this service will do, so I think trying to remove it from the scope is a tiny gain, which becomes a bigger cost binding yourself to another service and team.

**Comment by marcelosalloum** [comment]
Yep, I agree with that. I don't see any benefit on doing it and the cost of maintaining that will be hight.

@shanzzam: any reason for using https://testanchor.stellar.org/.well-known/stellar.toml?

**Comment by leighmcculloch** [comment]
One reason to use it would be if you wanted to provide approval for an asset anchored by another piece of software. Which raises the question, how will someone use the test/demo server? Will they run it configured with their own asset, and assume they can get the asset via their own faucet? Will they hit our deployment?

**Comment by marcelosalloum** [comment]
I think using the same server for both the TOML and the approval endpoint will make it easier for any party to use the SEP-8 server as they can have both in one service.

If we separate the TOML file from the approval server, anyone using our service will need to have additional work to handle the TOML file separately, which is not ideal IMO.

**Comment by marcelosalloum** [comment]
Also, there could be multiple different TOML files pointing to the same approval server, so serving a TOML file in the same server as the approval endpoint will not remove that possibility.

**Comment by marcelosalloum** [comment]
For this project I'm planning to implement a CLI helper that raises a `REGULATED_ASSET->XLM` offer. With this, users can get ahold of some  REGULATED_ASSET unities by making a `XLM->REGULATED_ASSET` offer.

**Comment by marcelosalloum** [comment]
This work should be finished now 🎉

**Comment by shanzzam** [comment]
Will review and wait for sign-off from @lydiat
